### ISSUE TITLE
サンプルサイト作成

### ISSUE THREAD

**Issue by yuichi-andi** [yuichi-andi/TTT#4]

**Comment by yuichi-andi** [comment]
＜ページ＞
・会社紹介
・オンラインショップ
・法人、個人ページの切り替え
・品質ページ
・OME問い合わせページ

**Comment by TsujiiDaichi** [comment]
### Aaa**aaaaaaaa**

**Comment by yuichi-andi** [comment]
https://ttt-jp.sakura.ne.jp/sample/

**Comment by yuichi-andi** [comment]
###画面遷移図
https://docs.google.com/spreadsheets/d/1LbUcxdIAieouTXNOqatpz4b7y9gNSUyPPXzRHbKfc84/edit?usp=sharing
